apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.service_namespace }}
  name: {{ .Release.Name }}-service
  labels:
    {{- include "hw3-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "hw3-chart.selectorLabels" . | nindent 4 }}
