replicaCount: 2

namespace: hw2

image:
  repository: wittlich
  name: arch-course-hw2
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

postgresql:
  user: "hw2_user"
  password: "123"
  database: "hw2"
  host: "postgres"
  port: "5432"

ingress:
  enabled: true
  className: ""
  annotations: {
    kubernetes.io/ingress.class: "nginx"
  }
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
