replicaCount: 1

service_namespace: hw3
monitoring_namespace: monitoring
ingress_namespace: ingress-nginx

image:
  repository: wittlich
  name: arch-course-hw3
  tag: v1
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 8000

metrics:
  serviceMonitor:
    enabled: true

postgresql:
  user: "hw3_user"
  password: "123"
  database: "hw3"
  host: "postgres"
  port: "5432"

ingress:
  enabled: true
  className: ""
  annotations: {
    kubernetes.io/ingress.class: "nginx"
  }
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
