{
 "title": "hw3",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_latency_bucket{}[1m]))"
    },
    {
     "expr": "histogram_quantile(0.5, rate(http_latency_bucket{}[1m]))"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_latency_bucket{}[1m]))"
    },
    {
     "expr": "histogram_quantile(1, rate(http_latency_bucket{}[1m]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_number{}[1m])) by (addr)"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "http_error_rate{}" }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_requests_total{}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{}[5m])) by (container)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"hw3\"}) by (pod) / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Postgres DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"hw3\"} / (1024 * 1024)"
    }
   ]
  }
 ]
}