{
 "title": "hw3",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{}[1m])) by (method, path)"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_requests_total{}[1m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, max by (le) (rate(http_request_duration_milliseconds_bucket{code=\"OK\"}[1m])))"
    },
    {
     "expr": "histogram_quantile(0.5, max by (le) (rate(http_request_duration_milliseconds_bucket{code=\"OK\"}[1m])))"
    },
    {
     "expr": "histogram_quantile(0.99, max by (le) (rate(http_request_duration_milliseconds_bucket{code=\"OK\"}[1m])))"
    },
    {
     "expr": "histogram_quantile(1, max by (le) (rate(http_request_duration_milliseconds_bucket{code=\"OK\"}[1m])))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_error_rate{}[1m])) by (code)"
    }
   ]
  },
  {
   "title": "Postgres DB Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"hw3\"} / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{}[5m])) by (container)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"hw3\"}) by (pod) / (1024 * 1024)"
    }
   ]
  }
 ]
}